services:
  backend:
    build: ./
    container_name: shop_container
    working_dir: /shop
    ports:
      - "8008:8000"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/shop/src
      - ./commands:/shop/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
#  nginx:
#    ...
#  redis:
#    ...
volumes:
  pg_data: { }