services:
  backend:
    build: ./
    container_name: shop_container
    working_dir: /shop
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    command:
      - ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/shop/src
      - ./commands:/shop/commands
      - static_content:/shop/src/static
      - media_content:/shop/src/media
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5000:80'
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres

#  mongodb:
#    image: mongo:noble
#    container_name: mongo_db
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#    env_file:
#      - .env
#    restart: on-failure

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/shop/src/static
      - media_content:/shop/src/media
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    depends_on:
      - backend

  redis:
    image: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend
  celery:
    build: ./
    container_name: celery_container
    command: ./commands/start_celery.sh
    restart: on-failure
    volumes:
      - ./src:/shop
      - ./commands:/shop/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend
  flower:
    build: ./
    container_name: flower_container
    volumes:
      - ./src:/shop
    env_file:
      - .env
    command: celery -A config flower --broker=redis://redis
    ports:
      - "5556:5555"
    depends_on:
      - celery

volumes:
  pg_data: { }
  pg_admin: { }
#  mongo_data: { }
  static_content: { }
  media_content: { }
